import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import ToastProvider from '@/components/ToastProvider'
import Navbar from '@/components/Navbar'
import ScrollButton from '@/components/ScrollButton'
import StoreProvider from './StoreProvider'
import ThemeProvider from './ThemeProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <StoreProvider>
          <ThemeProvider />
          <ToastProvider>
            <div className='flex flex-col'>
              {/* header */}
              <div className='w-full top-0 left-0 z-10 flex flex-col items-center bg-gray-200 bg-opacity-50 backdrop-blur-2xl'>
                <Navbar />
              </div>
              {/* header */}

              {/* main */}
              <div className='grow overflow-hidden'>{children}</div>
              {/* main */}
            </div>

            {/* Scroll button */}
            <ScrollButton />
            {/* Scroll button */}
          </ToastProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
